Preliminary work on separating SimpIR from CoreIR.
google-research/dex-lang pull request #1169
Opened 2022-11-25 14:00 UTC by axch

Method: Make `SimpIR` a separate (but isomorphic) IR constructor to `CoreIR` and fix compilation errors.

I didn't finish, so I rolled back the impetus change.  So, `SimpIR` is still an alias for `CoreIR`, but the correct one is referred to in more places.

The functional change is that attempting to `substE` at `(AtomSubstVal CoreIR)` into the `LoweredTopFun` constructor of `TopFunBinding` is now a runtime error, on the grounds that `LoweredTopFun` carries `SimpIR` (which I infer from its name and type-checking how it is constructed).  This runtime error does not occur in the test suite.

I encountered three problems that stopped me from making further progress:

**Custom Linearizations**

The content of a custom linearization rule is typed as `Atom CoreIR`, and at runtime is presumably always a lambda.  However, `linearize` just directly constructs an application thereof in `SimpIR`, using `naryApp`.

Is this just a bug?  Should we call `simplifyApp` from `linearizeExpr`?  (Maybe the only reason it isn't currently done that way is the circular module dependency it would cause between Simplify.hs and Linearize.hs.)

On the other hand, that `Atom CoreIR` is just the reconstruction of a definition that was already simplified (when the "create custom linearization" directive was processed).  Is there perhaps some reason to expect that such a reconstruction can just be added to `SimpIR` without trouble?  If so, should we express that reason to GHC?

**Simplification substitutions**

The simplifier's whole job is to change from `CoreIR` to `SimpIR`. However, the substitution it carries is typed `AtomSubstVal CoreIR`, so doesn't have a proof that it did its job!  I am somewhat confused by the comment about top-level function names being an exception; but whatever the exception is, perhaps we can express it to GHC?

**Reconstructions**

What is the IR typology of reconstructions and ReconAbs?  What information are they supposed to carry, and what are they even used for at the end of the day?  In particular, `applyRecon` seems to be used a lot to emit `SimpIR` inside `simplifyHof`, but `simplifyTopBlock` seems to want to be able to use the recon to carry `CoreIR`.

Is there a chance that this problem might be solved by capturing the constraint on where `Lam` atoms can appear after simplification, and what we know about their bodies before and after?  And maybe `Lam`s that float all the way to the top level are allowed to be different from those that stop at a `PrimHof`?

2022-11-30 15:35 UTC, dougalm requested changes
Thanks for trying this out and figuring out what we need to fix.

> However, linearize just directly constructs an application thereof in SimpIR

Actually, I think linearize should be producing CoreIR. The result of linearize gets subsequently simplified.

> The simplifier's whole job is to change from CoreIR to SimpIR. However, the substitution it carries is typed AtomSubstVal CoreIR, so doesn't have a proof that it did its job!

Right, I think the substitution needs to carry a third type of IR. Let's call it CoreToSimpIR. It allows CoreIR constructs like lambda (which it needs, since it's the mechanism for inlining these). But it contains `SimpIR` atoms as its "leaves". For any atom whose type is "data", it should be possible to translate the `Atom CoreToSimpIR` to `Atom SimpIR` without error.


> Reconstructions

Reconstructions are also a funny mix. They reconstruct Core atoms from Simp data.

2022-11-30 15:35 UTC, dougalm commented on src/lib/Types/Core.hs
> +instance SubstE (AtomSubstVal CoreIR) TopFunBinding where
Did you figure out why we even need this instance? I would expect that TopFunBinding would need `SubstE Name` and nothing else.

2022-11-30 15:35 UTC, dougalm commented on src/lib/Simplify.hs
> +newtype SimplifyMP (r::IR) (i::S) (o::S) (a:: *) = SimplifyM
I don't think we should make the simplification monad polymorphic in the IR parameter. I realize you did this to handle the `catch` traversal, but I think we should do it differently. To do IR-typed simplification properly, we'll want to have three IR variants at play: CoreIR for the IR that goes into simplification, SimpIR for the IR that comes out, and CoreToSimpIR for the substitution.  CoreToSimpIR will allow SimpIR atoms embedded within CoreIR atoms. I've been using this pattern for the Imp traversal and it works well: https://github.com/google-research/dex-lang/pull/1173.

2022-12-15 14:29 UTC, axch commented
Subsumed by #1179.

2022-12-15 14:29 UTC, closed without merging